#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker6"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "3b95b9b3da0d4409ad338a5d059366e5" }
]

[assets]
directory = "./public"
